#region Description
/*================================================================================
 *  Copyright (c) agile.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  BizOrg
 * Descrption:
 * CreateDate: 2010/11/18 13:55:35
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;


using AgileEAP.Core;
using AgileEAP.Core.Caching;
using AgileEAP.Core.Service;


using AgileEAP.Infrastructure.Domain;

namespace AgileEAP.Infrastructure.Service
{
    public class BizOrgService :  BaseService<string,BizOrg>
    {
		#region Fields
		private readonly ILogger log = LogManager.GetLogger(typeof(BizOrgService));
		#endregion
		
		#region Constructors
		
		public BizOrgService(){ }
		#endregion

        #region IBizOrgService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}