#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  PersonalParam
 * Descrption:
 * CreateDate: 2010/11/18 13:40:11
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;


using AgileEAP.Core;
using AgileEAP.Core.Caching;
using AgileEAP.Core.Service;


using AgileEAP.Infrastructure.Domain;

namespace AgileEAP.Infrastructure.Service
{
    public class PersonalParamService :  BaseService<string,PersonalParam>
    {
		#region Fields
		private readonly ILogger log = LogManager.GetLogger(typeof(PersonalParamService));
		#endregion
		
		#region Constructors
		
		public PersonalParamService(){ }
		#endregion

        #region IPersonalParamService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}