#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AgileEAP.Infrastructure
 * Module:  UploadFile
 * Descrption:
 * CreateDate: 2010/12/27 20:19:51
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;


using AgileEAP.Core;
using AgileEAP.Core.Caching;
using AgileEAP.Core.Service;


using AgileEAP.Infrastructure.Domain;

namespace AgileEAP.Infrastructure.Service
{
    public class UploadFileService : BaseService<string, UploadFile>
    {
        #region Fields
        private readonly ILogger log = LogManager.GetLogger(typeof(UploadFileService));
        #endregion

        #region Constructors

        public UploadFileService() { }
        #endregion

        #region IUploadFileService Imp

        #endregion

        #region Internal Methods

        #endregion
    }
}