#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AgileEAP.Infrastructure
 * Module:  Catalog
 * Descrption:
 * CreateDate: 2010/12/27 20:19:51
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;



using AgileEAP.Core;

using AgileEAP.Core.Service;
using AgileEAP.Core.Security;
using AgileEAP.Core.Extensions;
using AgileEAP.Core.Web;
using AgileEAP.Core.Caching;
using AgileEAP.Core.FastInvoker;

using AgileEAP.WebControls;
using AgileEAP.Infrastructure.Domain;
using AgileEAP.Infrastructure.Service;

namespace AgileEAP.Administration
{
    public partial class CatalogManager : BasePage
    {
        //private CatalogService catalogService=new CatalogService();

        //#region ---界面处理方法---

        ///// <summary>
        ///// 初始化页面
        ///// </summary>
        ///// <param name="e"></param>
        //protected override void OnInit(EventArgs e)
        //{
        //    base.OnInit(e);
        //    gvList.PageChanged += new PagedGridView.PagintEventHandler(gvList_PageChanged);
        //}

        //void gvList_PageChanged(object sender, PagingArgs e)
        //{
        //    ShowList(gvList,new PageInfo(e.PageIndex, e.PageSize, e.ItemCount));
        //}

        //protected void Page_Load(object sender, EventArgs e)
        //{
        //    if (!IsPostBack)
        //    {
        //        ShowList(gvList,new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
        //    }
        //}

        //#endregion

        //#region ---操作处理方法---
        ///// <summary>
        ///// 转向明细页面
        ///// </summary>
        ///// <param name="param"></param>
        //protected  void Redirect(string param)
        //{
        //    var currentIdParam = PageContext.Action == ActionType.Add ? string.Empty : string.Format("&CurrentId={0}", CurrentId);
        //    Response.Redirect(string.Format("CatalogDetail.aspx?LastUrl={0}&Runat=1&ActionFlag={1}{2}{3}", Request.Url.PathAndQuery, PageContext.Action, currentIdParam, string.IsNullOrEmpty(param) ? param : "&" + param));
        //}
		
        ///// <summary>
        ///// 新增
        ///// </summary>
        //public void Add()
        //{
        //    PageContext.Action = ActionType.Add;
        //    PageContext.PageIndex = gvList.PageIndex;
        //    SavePageContext(PageContext);

        //    Redirect(string.Empty);
        //}

        ///// <summary>
        ///// 查看
        ///// </summary>
        //public void View()
        //{
        //    PageContext.Action = ActionType.View;
        //    PageContext.PageIndex = gvList.PageIndex;
        //    SavePageContext(PageContext);

        //    Redirect(string.Empty);
        //}
		
        ///// <summary>
        ///// 修改
        ///// </summary>
        //public void Update()
        //{
        //    PageContext.Action = ActionType.Update;
        //    PageContext.PageIndex = gvList.PageIndex;
        //    SavePageContext(PageContext);
			
        //    Redirect(string.Empty);
        //}

        ///// <summary>
        ///// 刷新
        ///// </summary>
        //public void Refresh()
        //{
        //    ShowList(gvList,new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
        //}
	
        ///// <summary>
        ///// 显示列表信息
        ///// </summary>
        ///// <param name="gvList">GridView对象</param>
        ///// <param name="pageInfo">分页信息</param>
        //public void ShowList(PagedGridView gvList, PageInfo pageInfo)
        //{
        //    IPageOfList<Catalog> result = catalogService.FindAll(GetFilterParameters(), pageInfo);
        //    gvList.ItemCount = result.PageInfo.ItemCount;
        //    gvList.DataSource = result;
        //    gvList.DataBind();
        //}
        //#endregion
    }
}
