#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  SysParam
 * Descrption:
 * CreateDate: 2010/11/18 13:40:12
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;



using AgileEAP.Core;

using AgileEAP.Core.Service;
using AgileEAP.Core.Security;
using AgileEAP.Core.Extensions;
using AgileEAP.Core.Web;
using AgileEAP.Core.Caching;
using AgileEAP.Core.FastInvoker;

using AgileEAP.WebControls;
using AgileEAP.Infrastructure.Domain;
using AgileEAP.Infrastructure.Service;


namespace AgileEAP.Administration
{
    public partial class SysParamManager : BasePage
    {
        private SysParamService sysParamService = new SysParamService();

        #region ---界面处理方法---

        /// <summary>
        /// 初始化页面
        /// </summary>
        /// <param name="e"></param>
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            gvList.PageChanged += new PagedGridView.PagintEventHandler(gvList_PageChanged);
        }

        void gvList_PageChanged(object sender, PagingArgs e)
        {
            ShowList(gvList, new PageInfo(e.PageIndex, e.PageSize, e.ItemCount));
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                ShowList(gvList, new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
            }
        }

        #endregion

        #region ---操作处理方法---

        public string Delete(string id)
        {
            AjaxResult ajaxResult = new AjaxResult();

            string errorMsg = string.Empty;
            DoResult doResult = DoResult.Failed;
            string actionMessage = string.Empty;
            try
            {
                SysParam sysParam = sysParamService.GetDomain(id);
                if (!string.IsNullOrWhiteSpace(id))
                {
                    sysParamService.Delete(id);
                    sysParamService.ClearCache();

                    doResult = DoResult.Success;

                    //获取提示信息
                    actionMessage = RemarkAttribute.GetEnumRemark(doResult);

                    ajaxResult.Result = doResult;
                    ajaxResult.RetValue = CurrentId;
                    ajaxResult.PromptMsg = actionMessage;
                }
                AddActionLog<SysParam>(string.Format("删除系统参数{0}={1}", sysParam.Name, sysParam.Value), doResult);
            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(doResult);
                log.Error(actionMessage, ex);

            }

            return JsonConvert.SerializeObject(ajaxResult);
        }
        public string Save(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();

            string errorMsg = string.Empty;
            DoResult doResult = DoResult.Failed;
            string actionMessage = string.Empty;
            try
            {
                SysParam sysParam = JsonConvert.DeserializeObject<SysParam>(argument);

                //判断是否有相同的参数名存在
                Dictionary<string, object> param = new Dictionary<string, object>();
                param.Add("Name", sysParam.Name);
                var isParam = sysParamService.FindAll(param);
                if (isParam.Count > 0 && string.IsNullOrWhiteSpace(sysParam.ID))
                {
                    ajaxResult.PromptMsg = "此参数名称已存在！";
                    return JsonConvert.SerializeObject(ajaxResult);
                }
                if (string.IsNullOrEmpty(sysParam.ID))
                {
                    sysParam.ID = IdGenerator.NewComb().ToString();
                    sysParam.CreateTime = DateTime.Now;
                    sysParam.Creator = User.ID;
                    sysParamService.SaveOrUpdate(sysParam);
                }
                else
                {
                    sysParam.ModifyTime = DateTime.Now;
                    sysParam.Modifier = User.ID;
                    sysParamService.SaveOrUpdate(sysParam);
                }

                CacheManager.Remove(sysParam.Name);
                doResult = DoResult.Success;

                //获取提示信息
                actionMessage = string.Format("保存系统参数{0}成功", sysParam.Name);

                //记录操作日志
                AddActionLog(sysParam, doResult, actionMessage);

                ajaxResult.Result = doResult;
                ajaxResult.RetValue = sysParam.ID;
                ajaxResult.PromptMsg = actionMessage;

            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(doResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 查询
        /// </summary>
        public void Search()
        {
            ShowList(gvList, new PageInfo(1, gvList.PageSize, gvList.ItemCount));
        }

        /// <summary>
        /// 显示列表信息
        /// </summary>
        /// <param name="gvList">GridView对象</param>
        /// <param name="pageInfo">分页信息</param>
        public void ShowList(PagedGridView gvList, PageInfo pageInfo)
        {
            IPageOfList<SysParam> result = sysParamService.FindAll(GetFilterParameters(), pageInfo);
            gvList.ItemCount = result.PageInfo.ItemCount;
            gvList.DataSource = result;
            gvList.DataBind();
        }
        #endregion
    }
}
