#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  UploadFile
 * Descrption:
 * CreateDate: 2010/11/18 13:40:12
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;
using System.IO;



using AgileEAP.Core;
using AgileEAP.Core.Data;

using AgileEAP.Core.Service;
using AgileEAP.Core.Security;
using AgileEAP.Core.Extensions;
using AgileEAP.Core.Web;
using AgileEAP.Core.Caching;
using AgileEAP.Core.FastInvoker;

using AgileEAP.WebControls;
using AgileEAP.Infrastructure.Domain;
using AgileEAP.Infrastructure.Service;


namespace AgileEAP.Administration
{
    public partial class UploadFileManager : BasePage
    {
        private UploadFileService uploadFileService = new UploadFileService();
        private CatalogService catalogService = new CatalogService();

        #region ---界面处理方法---

        /// <summary>
        /// 初始化页面
        /// </summary>
        /// <param name="e"></param>
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            gvList.PageChanged += new PagedGridView.PagintEventHandler(gvList_PageChanged);
        }

        void gvList_PageChanged(object sender, PagingArgs e)
        {
            ShowList(gvList, new PageInfo(e.PageIndex, e.PageSize, e.ItemCount));
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                ShowPageDetail();
                ShowList(gvList, new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
            }
        }
        protected void ShowPageDetail()
        {
            Catalog parent = null;
            if (PageContext.Action == ActionType.Add)
            {
                parent = catalogService.GetDomain(Request.QueryString["ParentID"]);
                if (parent != null)
                {
                    chbParentID.Text = parent.CatalogName;
                    chbParentID.Value = parent.ID;
                    txtPath.Text = parent.Path;
                    hdnPath.Value = parent.Path;
                    hdnActionType.Value = "add";
                }
                return;
            }

            Catalog entity = catalogService.GetDomain(CurrentId);
            if (entity == null) return;

            SetControlValues(entity);

            parent = catalogService.GetDomain(entity.ParentID);
            if (parent != null)
            {
                chbParentID.Text = parent.CatalogName;
                chbParentID.Value = parent.ID;
                hdnPath.Value = parent.Path;
            }
        }

        #endregion

        #region ---操作处理方法---
        /// <summary>
        /// 转向明细页面
        /// </summary>
        /// <param name="param"></param>
        protected void Redirect(string param)
        {
            var currentIdParam = PageContext.Action == ActionType.Add ? string.Empty : string.Format("&CurrentId={0}", CurrentId);
            Response.Redirect(string.Format("UploadFileDetail.aspx?LastUrl={0}&Runat=1&ActionFlag={1}{2}{3}", Request.Url.PathAndQuery, PageContext.Action, currentIdParam, string.IsNullOrEmpty(param) ? param : "&" + param));
        }

        /// <summary>
        /// 新增
        /// </summary>
        public void Add()
        {
            PageContext.Action = ActionType.Add;
            PageContext.PageIndex = gvList.PageIndex;
            SavePageContext(PageContext);

            Redirect(string.Empty);
        }

        /// <summary>
        /// 查看
        /// </summary>
        public void View()
        {
            PageContext.Action = ActionType.View;
            PageContext.PageIndex = gvList.PageIndex;
            SavePageContext(PageContext);

            Redirect(string.Empty);
        }

        /// <summary>
        /// 修改
        /// </summary>
        public void Update()
        {
            PageContext.Action = ActionType.Update;
            PageContext.PageIndex = gvList.PageIndex;
            SavePageContext(PageContext);

            Redirect(string.Empty);
        }

        /// <summary>
        /// 刷新
        /// </summary>
        public void Refresh()
        {
            ShowList(gvList, new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
        }

        /// <summary>
        /// 查询
        /// </summary>
        public void Search()
        {
            ShowList(gvList, new PageInfo(1, gvList.PageSize, gvList.ItemCount));
        }
        /// <summary>
        /// 保存目录
        /// </summary>
        public string Save(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();

            string errorMsg = string.Empty;
            DoResult doResult = DoResult.Failed;
            string actionMessage = string.Empty;
            try
            {
                Catalog catalog = JsonConvert.DeserializeObject<Catalog>(argument);

                catalog.ID = string.IsNullOrWhiteSpace(CurrentId) ? IdGenerator.NewComb().ToString() : CurrentId;
                catalog.OwnerOrg =GetOrgCodePath(User.ID);// User.OrgPath;
                catalog.Creator = User.ID;

                catalogService.SaveOrUpdate(catalog);
                catalogService.ClearCache();

                string folderPath = Path.Combine(Server.MapPath("~"), catalog.Path);
                if (!Directory.Exists(folderPath))
                    Directory.CreateDirectory(folderPath);

                doResult = DoResult.Success;

                //获取提示信息
                actionMessage = string.Format("保存目录{0}成功", catalog.Path);

                //记录操作日志
                AddActionLog(catalog, doResult, actionMessage);

                ajaxResult.Result = doResult;
                ajaxResult.RetValue = catalog.ID;
                ajaxResult.PromptMsg = actionMessage;

            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(doResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 根据目录id获取目录路径
        /// </summary>
        public string GetPath(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();
            try
            {
                DoResult doResult = DoResult.Failed;
                if (!string.IsNullOrWhiteSpace(argument))
                {
                    Catalog catalog = catalogService.GetDomain(argument);
                    catalogService.ClearCache();

                    doResult = DoResult.Success;
                    ajaxResult.Result = doResult;
                    ajaxResult.RetValue = catalog.Path;
                }
            }
            catch (Exception ex)
            {
                log.Error("获取目录路径失败！", ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 删除目录下的文件
        /// </summary>
        public string Delete(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();

            string errorMsg = string.Empty;
            DoResult doResult = DoResult.Failed;
            string actionMessage = string.Empty;
            try
            {

                if (!string.IsNullOrWhiteSpace(argument))
                {
                    UploadFile uploadFile = uploadFileService.GetDomain(argument);
                    string filePath = Server.MapPath("~") + uploadFile.FilePath;

                    if (File.Exists(filePath))
                    {
                        File.Delete(filePath);  //删除文件物理路径
                    }

                    uploadFileService.Delete(argument);
                    uploadFileService.ClearCache();
                    doResult = DoResult.Success;
                    //获取提示信息
                    actionMessage = RemarkAttribute.GetEnumRemark(doResult);

                    ajaxResult.Result = doResult;
                    ajaxResult.RetValue = CurrentId;
                    ajaxResult.PromptMsg = actionMessage;

                }
            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(doResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 显示列表信息
        /// </summary>
        /// <param name="gvList">GridView对象</param>
        /// <param name="pageInfo">分页信息</param>
        public void ShowList(PagedGridView gvList, PageInfo pageInfo)
        {
            IDictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.SafeAdd("CatalogID", CurrentId);
            parameters.SafeAdd("dataFilter", new Condition(GetFilterString()));
            IPageOfList<UploadFile> result = uploadFileService.FindAll(parameters, "Order By FileName", pageInfo);
            gvList.ItemCount = result.PageInfo.ItemCount;
            gvList.DataSource = result;
            gvList.DataBind();
        }

        public string GetUserNameByUserId(string userId)
        {
            Operator operatorInfo =repository.GetDomain<Operator>(userId);
            if (operatorInfo != null)
            {
                return operatorInfo.UserName;
            }
            return "";
        }
        #endregion
    }
}
