#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  ActionLog
 * Descrption:
 * CreateDate: 2010/11/18 13:40:07
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;
using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;

namespace AgileEAP.Core.Log
{
    public partial class ActionLog : DomainObject<string>
    {
        #region Fields

        private string _userName = string.Empty;
        private short _logType = default(Int16);
        private string _clientIP = string.Empty;
        private string _appModule = string.Empty;
        private string _message = string.Empty;
        private short _result = default(Int16);
        private string _userID = string.Empty;
        private System.DateTime _createTime = DateTime.Now;


        #endregion

        #region Constructors
        public ActionLog() { }


        public ActionLog(string id, string userName, short logType, string clientIP, string appModule, string message, short result, string userID, System.DateTime createTime)
        {
            this.ID = id;
            this._userName = userName;
            this._logType = logType;
            this._clientIP = clientIP;
            this._appModule = appModule;
            this._message = message;
            this._result = result;
            this._userID = userID;
            this._createTime = createTime;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_userName);
            sb.Append(_logType);
            sb.Append(_clientIP);
            sb.Append(_appModule);
            sb.Append(_message);
            sb.Append(_result);
            sb.Append(_userID);
            sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 操作员名称
        /// </summary>
        public virtual string UserName
        {
            get { return _userName; }
            set { _userName = value; }
        }

        /// <summary>
        /// 日志类型
        /// </summary>
        public virtual short LogType
        {
            get { return _logType; }
            set { _logType = value; }
        }

        /// <summary>
        /// 操作机器IP
        /// </summary>
        public virtual string ClientIP
        {
            get { return _clientIP; }
            set { _clientIP = value; }
        }

        /// <summary>
        /// 应用名称
        /// </summary>
        public virtual string AppModule
        {
            get { return _appModule; }
            set { _appModule = value; }
        }

        /// <summary>
        /// 操作信息
        /// </summary>
        public virtual string Message
        {
            get { return _message; }
            set { _message = value; }
        }

        /// <summary>
        /// 1－成功，0－失败，2－系统异常，3-事务回滚
        /// </summary>
        public virtual short Result
        {
            get { return _result; }
            set { _result = value; }
        }

        /// <summary>
        /// 操作员ID
        /// </summary>
        public virtual string UserID
        {
            get { return _userID; }
            set { _userID = value; }
        }

        /// <summary>
        /// 操作时间
        /// </summary>
        public virtual System.DateTime CreateTime
        {
            get { return _createTime.ToSafeDateTime(); }
            set { _createTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 修改内容
        /// </summary>
        public virtual string Content
        {
            get;
            set;
        }
        #endregion
    }
}
