#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: workflow
 * Module:  workflow
 * Descrption:
 * CreateDate: 2010/1/27
 * Author: hgq
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



using AgileEAP.Core;

using AgileEAP.Core.Service;
using AgileEAP.Core.Security;
using AgileEAP.Core.Extensions;
using AgileEAP.Core.Web;
using AgileEAP.Core.Caching;
using AgileEAP.Core.FastInvoker;

using AgileEAP.WebControls;


using AgileEAP.Core.Data;
using AgileEAP.Workflow.Engine;
using AgileEAP.Workflow.Domain;
using AgileEAP.Workflow.Enums;

namespace AgileEAP.Plugin.Workflow
{
    public partial class MyWorkItem : BasePage
    {
        IWorkflowEngine workflowEngine = new WorkflowEngine();
        #region ---界面处理方法---

        /// <summary>
        /// 初始化页面
        /// </summary>
        /// <param name="e"></param>
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            gvList.PageChanged += new PagedGridView.PagintEventHandler(gvList_PageChanged);
        }

        void gvList_PageChanged(object sender, PagingArgs e)
        {
            ShowList(gvList, new PageInfo(e.PageIndex, e.PageSize, e.ItemCount));
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                ShowList(gvList, new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
            }
        }

        #endregion

        #region ---操作处理方法---
        /// <summary>
        /// 查询
        /// </summary>
        public void Search()
        {
            ShowList(gvList, new PageInfo(1, gvList.PageSize, gvList.ItemCount));
        }
        /// <summary>
        /// 刷新
        /// </summary>
        public void Refresh()
        {
            ShowList(gvList, new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
        }

        /// <summary>
        /// 显示列表信息
        /// </summary>
        /// <param name="gvList">GridView对象</param>
        /// <param name="pageInfo">分页信息</param>
        public void ShowList(PagedGridView gvList, PageInfo pageInfo)
        {
            IDictionary<string, object> parameters = GetFilterParameters();
            if (Request.QueryString["Entry"] == "WaitExecute")
            {
                parameters.SafeAdd("CurrentState", (short)WorkItemStatus.WaitExecute);
            }
            else if (Request.QueryString["Entry"] == "Compeleted")
            {
                parameters.SafeAdd("CurrentState", new Condition(string.Format(" CurrentState !={0}", (short)WorkItemStatus.WaitExecute)));
            }

            IPageOfList<WorkItem> result = IsAdmin ? repository.FindAll<WorkItem>(parameters, "order by CreateTime desc", pageInfo) : workflowEngine.GetMyWorkItems(User.ID, parameters, null, pageInfo);
            if (result != null)
            {
                gvList.IncludeRowDoubleClick = false;
                gvList.ItemCount = result.PageInfo.ItemCount;
                gvList.DataSource = result.OrderByDescending(o => o.StartTime);
                gvList.DataBind();
            }
        }

        #endregion
    }
}