#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  ActivityInst
 * Descrption:
 * CreateDate: 2010/11/18 14:21:44
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class ActivityInst :DomainObject<string>
    {
        #region Fields
		
		private string _name = string.Empty;
		private short _type = default(Int16);
		private short _currentState = default(Int16);
		private System.DateTime _startTime = DateTime.Now;
		private System.DateTime _endTime = DateTime.Now;
		private string _subProcessInstID = string.Empty;
		private string _activityDefID = string.Empty;
		private string _processInstID = string.Empty;
		private short _rollbackFlag = default(Int16);
		private string _description = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public ActivityInst(){}
		
		
		public ActivityInst(string id,string name,short type,short currentState,System.DateTime startTime,System.DateTime endTime,string subProcessInstID,string activityDefID,string processInstID,short rollbackFlag,string description,System.DateTime createTime)
		{
		  this.ID=id;
		this._name=name;
		this._type=type;
		this._currentState=currentState;
		this._startTime=startTime;
		this._endTime=endTime;
		this._subProcessInstID=subProcessInstID;
		this._activityDefID=activityDefID;
		this._processInstID=processInstID;
		this._rollbackFlag=rollbackFlag;
		this._description=description;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_name);
			sb.Append(_type);
			sb.Append(_currentState);
			sb.Append(_startTime);
			sb.Append(_endTime);
			sb.Append(_subProcessInstID);
			sb.Append(_activityDefID);
			sb.Append(_processInstID);
			sb.Append(_rollbackFlag);
			sb.Append(_description);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 名称
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 活动类型
        /// </summary>
		public virtual short Type
        {
            get { return  _type; }
			set	{	_type =  value;}
        }
		
		/// <summary>
        /// 当前状态
        /// </summary>
		public virtual short CurrentState
        {
            get { return  _currentState; }
			set	{	_currentState =  value;}
        }
		
		/// <summary>
        /// 启动时间
        /// </summary>
		public virtual System.DateTime StartTime
        {
            get { return  _startTime.ToSafeDateTime(); }
			set	{	_startTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 结束时间
        /// </summary>
		public virtual System.DateTime EndTime
        {
            get { return  _endTime.ToSafeDateTime(); }
			set	{	_endTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 子流程实例ID
        /// </summary>
		public virtual string SubProcessInstID
        {
            get { return  _subProcessInstID; }
			set	{	_subProcessInstID =  value;}
        }
		
		/// <summary>
        /// 活动定义ID
        /// </summary>
		public virtual string ActivityDefID
        {
            get { return  _activityDefID; }
			set	{	_activityDefID =  value;}
        }
		
		/// <summary>
        /// 所属流程实例
        /// </summary>
		public virtual string ProcessInstID
        {
            get { return  _processInstID; }
			set	{	_processInstID =  value;}
        }
		
		/// <summary>
        /// 回退标志
        /// </summary>
		public virtual short RollbackFlag
        {
            get { return  _rollbackFlag; }
			set	{	_rollbackFlag =  value;}
        }
		
		/// <summary>
        /// 描述
        /// </summary>
		public virtual string Description
        {
            get { return  _description; }
			set	{	_description =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
