#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  AgentItem
 * Descrption:
 * CreateDate: 2010/11/18 14:21:44
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class AgentItem :DomainObject<string>
    {
        #region Fields
		
		private short _type = default(Int16);
		private string _relatedBizID = string.Empty;
		private short _isValid = default(Int16);
		private short _agentPrivilege = default(Int16);
		private string _agentID = string.Empty;
		
		
        #endregion

        #region Constructors
		public AgentItem(){}
		
		
		public AgentItem(string id,short type,string relatedBizID,short isValid,short agentPrivilege,string agentID)
		{
		  this.ID=id;
		this._type=type;
		this._relatedBizID=relatedBizID;
		this._isValid=isValid;
		this._agentPrivilege=agentPrivilege;
		this._agentID=agentID;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_type);
			sb.Append(_relatedBizID);
			sb.Append(_isValid);
			sb.Append(_agentPrivilege);
			sb.Append(_agentID);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 代理项类型
        /// </summary>
		public virtual short Type
        {
            get { return  _type; }
			set	{	_type =  value;}
        }
		
		/// <summary>
        /// 代理业务ID
        /// </summary>
		public virtual string RelatedBizID
        {
            get { return  _relatedBizID; }
			set	{	_relatedBizID =  value;}
        }
		
		/// <summary>
        /// 是否生效
        /// </summary>
		public virtual short IsValid
        {
            get { return  _isValid; }
			set	{	_isValid =  value;}
        }
		
		/// <summary>
        /// 代理权限
        /// </summary>
		public virtual short AgentPrivilege
        {
            get { return  _agentPrivilege; }
			set	{	_agentPrivilege =  value;}
        }
		
		/// <summary>
        /// 所属代理
        /// </summary>
		public virtual string AgentID
        {
            get { return  _agentID; }
			set	{	_agentID =  value;}
        }
		
        #endregion
    }
}
