#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  AgentCandidate
 * Descrption:
 * CreateDate: 2010/11/18 14:21:44
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class AgentCandidate :DomainObject<string>
    {
        #region Fields
		
		private string _agentToID = string.Empty;
		private string _agentToName = string.Empty;
		private short _agentToType = default(Int16);
		private string _agentFrom = string.Empty;
		
		
        #endregion

        #region Constructors
		public AgentCandidate(){}
		
		
		public AgentCandidate(string id,string agentToID,string agentToName,short agentToType,string agentFrom)
		{
		  this.ID=id;
		this._agentToID=agentToID;
		this._agentToName=agentToName;
		this._agentToType=agentToType;
		this._agentFrom=agentFrom;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_agentToID);
			sb.Append(_agentToName);
			sb.Append(_agentToType);
			sb.Append(_agentFrom);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 代理人
        /// </summary>
		public virtual string AgentToID
        {
            get { return  _agentToID; }
			set	{	_agentToID =  value;}
        }
		
		/// <summary>
        /// 代理人名称
        /// </summary>
		public virtual string AgentToName
        {
            get { return  _agentToName; }
			set	{	_agentToName =  value;}
        }
		
		/// <summary>
        /// 代理人类型
        /// </summary>
		public virtual short AgentToType
        {
            get { return  _agentToType; }
			set	{	_agentToType =  value;}
        }
		
		/// <summary>
        /// 委托人ID
        /// </summary>
		public virtual string AgentFrom
        {
            get { return  _agentFrom; }
			set	{	_agentFrom =  value;}
        }
		
        #endregion
    }
}
