#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  Participant
 * Descrption:
 * CreateDate: 2010/11/18 14:21:44
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class Participant :DomainObject<string>
    {
        #region Fields
		
		private string _name = string.Empty;
		private short _participantType = default(Int16);
		private string _participantID = string.Empty;
		private string _workItemID = string.Empty;
		private short _workItemState = default(Int16);
		private short _partiInType = default(Int16);
		private short _delegateType = default(Int16);
		private int _participantIndex = default(Int32);
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public Participant(){}
		
		
		public Participant(string id,string name,short participantType,string participantID,string workItemID,short workItemState,short partiInType,short delegateType,int participantIndex,System.DateTime createTime)
		{
		  this.ID=id;
		this._name=name;
		this._participantType=participantType;
		this._participantID=participantID;
		this._workItemID=workItemID;
		this._workItemState=workItemState;
		this._partiInType=partiInType;
		this._delegateType=delegateType;
		this._participantIndex=participantIndex;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_name);
			sb.Append(_participantType);
			sb.Append(_participantID);
			sb.Append(_workItemID);
			sb.Append(_workItemState);
			sb.Append(_partiInType);
			sb.Append(_delegateType);
			sb.Append(_participantIndex);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 名称
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 参与者类型
        /// </summary>
		public virtual short ParticipantType
        {
            get { return  _participantType; }
			set	{	_participantType =  value;}
        }
		
		/// <summary>
        /// 参与者值ID
        /// </summary>
		public virtual string ParticipantID
        {
            get { return  _participantID; }
			set	{	_participantID =  value;}
        }
		
		/// <summary>
        /// 工作项ID
        /// </summary>
		public virtual string WorkItemID
        {
            get { return  _workItemID; }
			set	{	_workItemID =  value;}
        }
		
		/// <summary>
        /// 工作项状态
        /// </summary>
		public virtual short WorkItemState
        {
            get { return  _workItemState; }
			set	{	_workItemState =  value;}
        }
		
		/// <summary>
        /// 参与类型
        /// </summary>
		public virtual short PartiInType
        {
            get { return  _partiInType; }
			set	{	_partiInType =  value;}
        }
		
		/// <summary>
        /// 代办类型
        /// </summary>
		public virtual short DelegateType
        {
            get { return  _delegateType; }
			set	{	_delegateType =  value;}
        }
		
		/// <summary>
        /// 参与顺序
        /// </summary>
		public virtual int ParticipantIndex
        {
            get { return  _participantIndex; }
			set	{	_participantIndex =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
