#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  ProcessDef
 * Descrption:
 * CreateDate: 2010/11/18 14:21:45
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class ProcessDef :DomainObject<string>
    {
        #region Fields
		
		private string _name = string.Empty;
		private string _text = string.Empty;
		private string _content = string.Empty;
		private string _categoryID = string.Empty;
		private short _currentState = default(Int16);
		private short _currentFlag = default(Int16);
		private string _startor = string.Empty;
		private short _isActive = default(Int16);
		private string _version = string.Empty;
		private string _description = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		private string _creator = string.Empty;
		private System.DateTime _modifyTime = DateTime.Now;
		private string _modifier = string.Empty;
		
		
        #endregion

        #region Constructors
		public ProcessDef(){}
		
		
		public ProcessDef(string id,string name,string text,string content,string categoryID,short currentState,short currentFlag,string startor,short isActive,string version,string description,System.DateTime createTime,string creator,System.DateTime modifyTime,string modifier)
		{
		  this.ID=id;
		this._name=name;
		this._text=text;
		this._content=content;
		this._categoryID=categoryID;
		this._currentState=currentState;
		this._currentFlag=currentFlag;
		this._startor=startor;
		this._isActive=isActive;
		this._version=version;
		this._description=description;
		this._createTime=createTime;
		this._creator=creator;
		this._modifyTime=modifyTime;
		this._modifier=modifier;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_name);
			sb.Append(_text);
			sb.Append(_content);
			sb.Append(_categoryID);
			sb.Append(_currentState);
			sb.Append(_currentFlag);
			sb.Append(_startor);
			sb.Append(_isActive);
			sb.Append(_version);
			sb.Append(_description);
			sb.Append(_createTime);
			sb.Append(_creator);
			sb.Append(_modifyTime);
			sb.Append(_modifier);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 名称
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 显示名
        /// </summary>
		public virtual string Text
        {
            get { return  _text; }
			set	{	_text =  value;}
        }
		
		/// <summary>
        /// 流程内容
        /// </summary>
		public virtual string Content
        {
            get { return  _content; }
			set	{	_content =  value;}
        }
		
		/// <summary>
        /// 所属分类
        /// </summary>
		public virtual string CategoryID
        {
            get { return  _categoryID; }
			set	{	_categoryID =  value;}
        }
		
		/// <summary>
        /// 当前状态
        /// </summary>
		public virtual short CurrentState
        {
            get { return  _currentState; }
			set	{	_currentState =  value;}
        }
		
		/// <summary>
        /// 是否当前版本
        /// </summary>
		public virtual short CurrentFlag
        {
            get { return  _currentFlag; }
			set	{	_currentFlag =  value;}
        }
		
		/// <summary>
        /// 流程启动者
        /// </summary>
		public virtual string Startor
        {
            get { return  _startor; }
			set	{	_startor =  value;}
        }
		
		/// <summary>
        /// 是否有活动实例
        /// </summary>
		public virtual short IsActive
        {
            get { return  _isActive; }
			set	{	_isActive =  value;}
        }
		
		/// <summary>
        /// 版本
        /// </summary>
		public virtual string Version
        {
            get { return  _version; }
			set	{	_version =  value;}
        }
		
		/// <summary>
        /// 描述
        /// </summary>
		public virtual string Description
        {
            get { return  _description; }
			set	{	_description =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 修改时间
        /// </summary>
		public virtual System.DateTime ModifyTime
        {
            get { return  _modifyTime.ToSafeDateTime(); }
			set	{	_modifyTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 修改人
        /// </summary>
		public virtual string Modifier
        {
            get { return  _modifier; }
			set	{	_modifier =  value;}
        }
		
        #endregion
    }
}
