#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  TraceLog
 * Descrption:
 * CreateDate: 2010/11/18 14:21:45
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class TraceLog : DomainObject<string>
    {
        #region Fields

        private short _actionType = default(Int16);
        private string _operator = string.Empty;
        private string _clientIP = string.Empty;
        private string _processID = string.Empty;
        private string _processInstID = string.Empty;
        private string _activityID = string.Empty;
        private string _activityInstID = string.Empty;
        private string _workItemID = string.Empty;
        private string _message = string.Empty;


        #endregion

        #region Constructors
        public TraceLog() { }


        public TraceLog(string id, short actionType, string _operator, string clientIP, string processID, string processInstID, string activityID, string activityInstID, string workItemID, string message)
        {
            this.ID = id;
            this._actionType = actionType;
            this._operator = _operator;
            this._clientIP = clientIP;
            this._processID = processID;
            this._processInstID = processInstID;
            this._activityID = activityID;
            this._activityInstID = activityInstID;
            this._workItemID = workItemID;
            this._message = message;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_actionType);
            sb.Append(_operator);
            sb.Append(_clientIP);
            sb.Append(_processID);
            sb.Append(_processInstID);
            sb.Append(_activityID);
            sb.Append(_activityInstID);
            sb.Append(_workItemID);
            sb.Append(_message);

            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 操作
        /// </summary>
        public virtual short ActionType
        {
            get { return _actionType; }
            set { _actionType = value; }
        }

        /// <summary>
        /// 操作人
        /// </summary>
        public virtual string Operator
        {
            get { return _operator; }
            set { _operator = value; }
        }

        /// <summary>
        /// IP地址
        /// </summary>
        public virtual string ClientIP
        {
            get { return _clientIP; }
            set { _clientIP = value; }
        }

        /// <summary>
        /// 流程ID
        /// </summary>
        public virtual string ProcessID
        {
            get { return _processID; }
            set { _processID = value; }
        }

        /// <summary>
        /// 流程实例ID
        /// </summary>
        public virtual string ProcessInstID
        {
            get { return _processInstID; }
            set { _processInstID = value; }
        }

        /// <summary>
        /// 活动ID
        /// </summary>
        public virtual string ActivityID
        {
            get { return _activityID; }
            set { _activityID = value; }
        }

        /// <summary>
        /// 活动实例ID
        /// </summary>
        public virtual string ActivityInstID
        {
            get { return _activityInstID; }
            set { _activityInstID = value; }
        }

        /// <summary>
        /// 工作项ID
        /// </summary>
        public virtual string WorkItemID
        {
            get { return _workItemID; }
            set { _workItemID = value; }
        }

        /// <summary>
        /// 消息
        /// </summary>
        public virtual string Message
        {
            get { return _message; }
            set { _message = value; }
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateTime
        {
            get;
            set;
        }
        #endregion
    }
}
