#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  Transition
 * Descrption:
 * CreateDate: 2010/11/18 14:21:45
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class Transition :DomainObject<string>
    {
        #region Fields
		
		private string _srcActID = string.Empty;
		private string _srcActInstID = string.Empty;
		private string _srcActInstName = string.Empty;
		private string _srcActName = string.Empty;
		private string _destActInstID = string.Empty;
		private string _destActInstName = string.Empty;
		private string _destActID = string.Empty;
		private string _destActName = string.Empty;
		private string _processInstID = string.Empty;
		private System.DateTime _transTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public Transition(){}
		
		
		public Transition(string id,string srcActID,string srcActInstID,string srcActInstName,string srcActName,string destActInstID,string destActInstName,string destActID,string destActName,string processInstID,System.DateTime transTime)
		{
		  this.ID=id;
		this._srcActID=srcActID;
		this._srcActInstID=srcActInstID;
		this._srcActInstName=srcActInstName;
		this._srcActName=srcActName;
		this._destActInstID=destActInstID;
		this._destActInstName=destActInstName;
		this._destActID=destActID;
		this._destActName=destActName;
		this._processInstID=processInstID;
		this._transTime=transTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_srcActID);
			sb.Append(_srcActInstID);
			sb.Append(_srcActInstName);
			sb.Append(_srcActName);
			sb.Append(_destActInstID);
			sb.Append(_destActInstName);
			sb.Append(_destActID);
			sb.Append(_destActName);
			sb.Append(_processInstID);
			sb.Append(_transTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 源活动定义ID
        /// </summary>
		public virtual string SrcActID
        {
            get { return  _srcActID; }
			set	{	_srcActID =  value;}
        }
		
		/// <summary>
        /// 源活动ID
        /// </summary>
		public virtual string SrcActInstID
        {
            get { return  _srcActInstID; }
			set	{	_srcActInstID =  value;}
        }
		
		/// <summary>
        /// 源活动名称
        /// </summary>
		public virtual string SrcActInstName
        {
            get { return  _srcActInstName; }
			set	{	_srcActInstName =  value;}
        }
		
		/// <summary>
        /// 源活动定义名称
        /// </summary>
		public virtual string SrcActName
        {
            get { return  _srcActName; }
			set	{	_srcActName =  value;}
        }
		
		/// <summary>
        /// 目标活动ID
        /// </summary>
		public virtual string DestActInstID
        {
            get { return  _destActInstID; }
			set	{	_destActInstID =  value;}
        }
		
		/// <summary>
        /// 目标活动名称
        /// </summary>
		public virtual string DestActInstName
        {
            get { return  _destActInstName; }
			set	{	_destActInstName =  value;}
        }
		
		/// <summary>
        /// 目标活动定义ID
        /// </summary>
		public virtual string DestActID
        {
            get { return  _destActID; }
			set	{	_destActID =  value;}
        }
		
		/// <summary>
        /// 目标活动定义名称
        /// </summary>
		public virtual string DestActName
        {
            get { return  _destActName; }
			set	{	_destActName =  value;}
        }
		
		/// <summary>
        /// 流程实例ID
        /// </summary>
		public virtual string ProcessInstID
        {
            get { return  _processInstID; }
			set	{	_processInstID =  value;}
        }

        		
		/// <summary>
        /// 流程实例ID
        /// </summary>
        public virtual string ProcessInstName
        {
            get;
            set;
        }
        
		
		/// <summary>
        /// 迁移时间
        /// </summary>
		public virtual System.DateTime TransTime
        {
            get { return  _transTime.ToSafeDateTime(); }
			set	{	_transTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
