#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  WorkItem
 * Descrption:
 * CreateDate: 2010/11/18 14:21:45
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Workflow.Domain
{
    [Serializable]
    public partial class WorkItem : DomainObject<string>
    {
        #region Fields

        private string _name = string.Empty;
        private short _type = default(Int16);
        private System.DateTime _createTime = DateTime.Now;
        private string _creator = string.Empty;
        private System.DateTime _startTime = DateTime.Now;
        private System.DateTime _endTime = DateTime.Now;
        private string _description = string.Empty;
        private short _currentState = default(Int16);
        private string _participant = string.Empty;
        private short _isTimeOut = default(Int16);
        private System.DateTime _timeOutTime = DateTime.Now;
        private System.DateTime _remindTime = DateTime.Now;
        private string _actionURL = string.Empty;
        private string _actionMask = string.Empty;
        private string _processInstID = string.Empty;
        private string _processInstName = string.Empty;
        private string _activityInstID = string.Empty;
        private string _activityInstName = string.Empty;
        private string _processID = string.Empty;
        private string _processText = string.Empty;
        private short _allowAgent = default(Int16);
        private short _bizState = default(Int16);
        private string _executor = string.Empty;
        private string _rootProcessInstID = string.Empty;
        private DateTime? _executeTime = DateTime.Now;


        #endregion

        #region Constructors
        public WorkItem() { }


        public WorkItem(string id, string name, short type, System.DateTime createTime, string creator, System.DateTime startTime, System.DateTime endTime, string description, short currentState, string participant, short isTimeOut, System.DateTime timeOutTime, System.DateTime remindTime, string actionURL, string actionMask, string processInstID, string processInstName, string activityInstID, string activityInstName, string processID, string processText, short allowAgent, short bizState, string executor, string rootProcessInstID)
        {
            this.ID = id;
            this._name = name;
            this._type = type;
            this._createTime = createTime;
            this._creator = creator;
            this._startTime = startTime;
            this._endTime = endTime;
            this._description = description;
            this._currentState = currentState;
            this._participant = participant;
            this._isTimeOut = isTimeOut;
            this._timeOutTime = timeOutTime;
            this._remindTime = remindTime;
            this._actionURL = actionURL;
            this._actionMask = actionMask;
            this._processInstID = processInstID;
            this._processInstName = processInstName;
            this._activityInstID = activityInstID;
            this._activityInstName = activityInstName;
            this._processID = processID;
            this._processText = processText;
            this._allowAgent = allowAgent;
            this._bizState = bizState;
            this._executor = executor;
            this._rootProcessInstID = rootProcessInstID;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_name);
            sb.Append(_type);
            sb.Append(_createTime);
            sb.Append(_creator);
            sb.Append(_startTime);
            sb.Append(_endTime);
            sb.Append(_description);
            sb.Append(_currentState);
            sb.Append(_participant);
            sb.Append(_isTimeOut);
            sb.Append(_timeOutTime);
            sb.Append(_remindTime);
            sb.Append(_actionURL);
            sb.Append(_actionMask);
            sb.Append(_processInstID);
            sb.Append(_processInstName);
            sb.Append(_activityInstID);
            sb.Append(_activityInstName);
            sb.Append(_processID);
            sb.Append(_processText);
            sb.Append(_allowAgent);
            sb.Append(_bizState);
            sb.Append(_executor);
            sb.Append(_rootProcessInstID);

            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 名称
        /// </summary>
        public virtual string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        /// 工作项类型
        /// </summary>
        public virtual short Type
        {
            get { return _type; }
            set { _type = value; }
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual System.DateTime CreateTime
        {
            get { return _createTime.ToSafeDateTime(); }
            set { _createTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 创建者
        /// </summary>
        public virtual string Creator
        {
            get { return _creator; }
            set { _creator = value; }
        }

        /// <summary>
        /// 启动时间
        /// </summary>
        public virtual System.DateTime StartTime
        {
            get { return _startTime.ToSafeDateTime(); }
            set { _startTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 结束时间
        /// </summary>
        public virtual System.DateTime EndTime
        {
            get { return _endTime.ToSafeDateTime(); }
            set { _endTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        /// <summary>
        /// 当前状态
        /// </summary>
        public virtual short CurrentState
        {
            get { return _currentState; }
            set { _currentState = value; }
        }

        /// <summary>
        /// 参与者
        /// </summary>
        public virtual string Participant
        {
            get { return _participant; }
            set { _participant = value; }
        }

        /// <summary>
        /// 是否超时
        /// </summary>
        public virtual short IsTimeOut
        {
            get { return _isTimeOut; }
            set { _isTimeOut = value; }
        }

        /// <summary>
        /// 超时时间
        /// </summary>
        public virtual System.DateTime TimeOutTime
        {
            get { return _timeOutTime.ToSafeDateTime(); }
            set { _timeOutTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 提醒时间
        /// </summary>
        public virtual System.DateTime RemindTime
        {
            get { return _remindTime.ToSafeDateTime(); }
            set { _remindTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 响应URL
        /// </summary>
        public virtual string ActionURL
        {
            get { return _actionURL; }
            set { _actionURL = value; }
        }

        /// <summary>
        /// 操作码
        /// </summary>
        public virtual string ActionMask
        {
            get { return _actionMask; }
            set { _actionMask = value; }
        }

        /// <summary>
        /// 所属流程实例
        /// </summary>
        public virtual string ProcessInstID
        {
            get { return _processInstID; }
            set { _processInstID = value; }
        }

        /// <summary>
        /// 所属流程实例名
        /// </summary>
        public virtual string ProcessInstName
        {
            get { return _processInstName; }
            set { _processInstName = value; }
        }

        /// <summary>
        /// 所属活动实例
        /// </summary>
        public virtual string ActivityInstID
        {
            get { return _activityInstID; }
            set { _activityInstID = value; }
        }

        /// <summary>
        /// 所属活动实像名
        /// </summary>
        public virtual string ActivityInstName
        {
            get { return _activityInstName; }
            set { _activityInstName = value; }
        }

        /// <summary>
        /// 所属流程
        /// </summary>
        public virtual string ProcessID
        {
            get { return _processID; }
            set { _processID = value; }
        }

        /// <summary>
        /// 所属流程显示名
        /// </summary>
        public virtual string ProcessName
        {
            get { return _processText; }
            set { _processText = value; }
        }

        /// <summary>
        /// 是否允许代理
        /// </summary>
        public virtual short AllowAgent
        {
            get { return _allowAgent; }
            set { _allowAgent = value; }
        }

        /// <summary>
        /// 业务状态
        /// </summary>
        public virtual short BizState
        {
            get { return _bizState; }
            set { _bizState = value; }
        }

        /// <summary>
        /// 工作项当前执行者
        /// </summary>
        public virtual string Executor
        {
            get { return _executor; }
            set { _executor = value; }
        }

        /// <summary>
        /// 工作项当前执行者提交时间
        /// </summary>
        public virtual DateTime? ExecuteTime
        {
            get { return _executeTime; }
            set { _executeTime = value; }
        }

        /// <summary>
        /// 所属根流程实例
        /// </summary>
        public virtual string RootProcessInstID
        {
            get { return _rootProcessInstID; }
            set { _rootProcessInstID = value; }
        }

        /// <summary>
        /// 创建者姓名
        /// </summary>
        public virtual string CreatorName
        {
            get;
            set;
        }

        /// <summary>
        /// 执行者姓名
        /// </summary>
        public virtual string ExecutorName
        {
            get;
            set;
        }
        #endregion
    }
}
