#region Description
/*================================================================================
 *  Copyright (c) agile.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  ObjectRole
 * Descrption:
 * CreateDate: 2010/11/18 13:55:37
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;



using AgileEAP.Core;
using AgileEAP.Core.Data;

using AgileEAP.Core.Service;
using AgileEAP.Core.Security;
using AgileEAP.Core.Extensions;
using AgileEAP.Core.Web;
using AgileEAP.Core.Caching;
using AgileEAP.Core.FastInvoker;

using AgileEAP.WebControls;
using AgileEAP.Infrastructure.Domain;
using AgileEAP.Infrastructure.Service;



namespace AgileEAP.Plugin.Authorize
{
    public partial class ObjectRoleManager : BasePage
    {

        #region ---界面处理方法---

        /// <summary>
        /// 初始化页面
        /// </summary>
        /// <param name="e"></param>
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
        }


        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                InitTree();
            }
        }

        #endregion

        #region ---操作处理方法---


        private void InitTree()
        {
            AjaxTree1.PostType = PostType.NoPost;
            AjaxTree1.IsAjaxLoad = false;
            AjaxTree1.ShowNodeIco = false;
            AjaxTree1.ShowCheckBox = true;
            AjaxTree1.Nodes.Clear();

            IDictionary<string, object> para = new Dictionary<string, object>();
            para.SafeAdd("OwnerOrg", new Condition(string.Format("OwnerOrg like '{0}%'", GetOrgPath())));
            IList<Role> roles = (User.UserType == (short)UserType.Administrator) ? repository.All<Role>() : repository.FindAll<Role>(para);
            string userID = Request.QueryString["UserID"];
            para.Clear();
            para.Add("ObjectID", userID);
            IList<string> objectRoleIDs = repository.FindAll<ObjectRole>(para).Select(o => o.RoleID).ToList<string>();


            foreach (var role in roles)
            {
                AjaxTreeNode node = new AjaxTreeNode()
                {
                    ID = role.ID,
                    Text = role.Name,
                    Value = role.ID,
                    Checked = objectRoleIDs.Contains(role.ID)
                };

                AjaxTree1.Nodes.Add(node);
            }
        }


        public string Save(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();
            try
            {


                IList<AjaxTreeNode> parameters = JsonConvert.DeserializeObject<IList<AjaxTreeNode>>(argument);

                string userID = Request.QueryString["UserID"];

                if (string.IsNullOrEmpty(userID))
                {
                    ajaxResult.Result = DoResult.Failed;
                    ajaxResult.PromptMsg = "用户对象为空！";
                    log.Error("角色ID为空");
                    return JsonConvert.SerializeObject(ajaxResult);
                }

                if (parameters == null || parameters.Count == 0)
                {
                    ajaxResult.PromptMsg = "您没有选择任何角色，请选择后再保存！";
                    return JsonConvert.SerializeObject(ajaxResult);
                }

                IList<ObjectRole> userRoles = parameters.Select(p => new ObjectRole()
                {
                    ID = IdGenerator.NewComb().ToSafeString(),
                    RoleID = p.Value,
                    ObjectID = userID
                }).ToList();

                new AuthorizeService().SaveObjectRoles(userRoles);
                ajaxResult.RetValue = string.Empty;
                ajaxResult.Result = DoResult.Success;
                ajaxResult.PromptMsg = "保存成功！";
            }
            catch (Exception ex)
            {
                ajaxResult.Result = DoResult.Failed;
                ajaxResult.PromptMsg = "保存角色出错，请联系管理员！";
                log.Error(ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }



        #endregion
    }
}
