#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  CacheData
 * Descrption:
 * CreateDate: 2010/11/18 13:40:09
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class CacheData :DomainObject<string>
    {
        #region Fields
		
		private string _name = string.Empty;
		private string _value = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		private System.DateTime _expireTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public CacheData(){}
		
		
		public CacheData(string id,string name,string value,System.DateTime createTime,System.DateTime expireTime)
		{
		  this.ID=id;
		this._name=name;
		this._value=value;
		this._createTime=createTime;
		this._expireTime=expireTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_name);
			sb.Append(_value);
			sb.Append(_createTime);
			sb.Append(_expireTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 缓存名
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 缓存值
        /// </summary>
		public virtual string Value
        {
            get { return  _value; }
			set	{	_value =  value;}
        }
		
		/// <summary>
        /// 生效时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 失效时间
        /// </summary>
		public virtual System.DateTime ExpireTime
        {
            get { return  _expireTime.ToSafeDateTime(); }
			set	{	_expireTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
