#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  App
 * Descrption:
 * CreateDate: 2010/11/23 10:05:33
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;

namespace AgileEAP.Infrastructure.Domain
{
    public partial class eForm : DomainObject<string>
    {

        /// <summary>
        /// 应用名
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

        /// <summary>
        /// 应用内容
        /// </summary>
        public virtual string Content
        {
            get;
            set;
        }

        /// <summary>
        /// 应用域
        /// </summary>
        public virtual string AppID
        {
            get;
            set;
        }

        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }


        /// <summary>
        /// 创建者
        /// </summary>
        public virtual string Creator
        {
            get;
            set;
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual System.DateTime CreateTime
        {
            get;
            set;
        }
    }
}
