#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  EmployeeOrg
 * Descrption:
 * CreateDate: 2010/11/18 13:55:36
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class EmployeeOrg :DomainObject<string>
    {
        #region Fields
		
		private string _orgID = string.Empty;
		private string _employeeID = string.Empty;
		private short _isMajor = default(Int16);
		
		
        #endregion

        #region Constructors
		public EmployeeOrg(){}
		
		
		public EmployeeOrg(string id,string orgID,string employeeID,short isMajor)
		{
		  this.ID=id;
		this._orgID=orgID;
		this._employeeID=employeeID;
		this._isMajor=isMajor;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_orgID);
			sb.Append(_employeeID);
			sb.Append(_isMajor);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 机构ID
        /// </summary>
		public virtual string OrgID
        {
            get { return  _orgID; }
			set	{	_orgID =  value;}
        }
		
		/// <summary>
        /// 人员ID
        /// </summary>
		public virtual string EmployeeID
        {
            get { return  _employeeID; }
			set	{	_employeeID =  value;}
        }
		
		/// <summary>
        /// 是否主机构
        /// </summary>
		public virtual short IsMajor
        {
            get { return  _isMajor; }
			set	{	_isMajor =  value;}
        }
		
        #endregion
    }
}
