#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  EmployeePosition
 * Descrption:
 * CreateDate: 2010/11/18 13:55:36
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class EmployeePosition :DomainObject<string>
    {
        #region Fields
		
		private string _positionID = string.Empty;
		private string _employeeID = string.Empty;
		private short _isMajor = default(Int16);
		
		
        #endregion

        #region Constructors
		public EmployeePosition(){}
		
		
		public EmployeePosition(string id,string positionID,string employeeID,short isMajor)
		{
		  this.ID=id;
		this._positionID=positionID;
		this._employeeID=employeeID;
		this._isMajor=isMajor;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_positionID);
			sb.Append(_employeeID);
			sb.Append(_isMajor);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 岗位编号
        /// </summary>
		public virtual string PositionID
        {
            get { return  _positionID; }
			set	{	_positionID =  value;}
        }
		
		/// <summary>
        /// 人员编号
        /// </summary>
		public virtual string EmployeeID
        {
            get { return  _employeeID; }
			set	{	_employeeID =  value;}
        }
		
		/// <summary>
        /// 是否主岗位
        /// </summary>
		public virtual short IsMajor
        {
            get { return  _isMajor; }
			set	{	_isMajor =  value;}
        }
		
        #endregion
    }
}
