#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  Module
 * Descrption:
 * CreateDate: 2010/11/23 10:05:34
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class Module :DomainObject<string>
    {
        #region Fields
		
		private string _name = string.Empty;
		private string _appID = string.Empty;
		private string _text = string.Empty;
		private string _assembly = string.Empty;
		private string _namesapce = string.Empty;
		private short _isValid = default(Int16);
		private string _description = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public Module(){}
		
		
		public Module(string id,string name,string appID,string text,string assembly,string namesapce,short isValid,string description,string creator,System.DateTime createTime)
		{
		  this.ID=id;
		this._name=name;
		this._appID=appID;
		this._text=text;
		this._assembly=assembly;
		this._namesapce=namesapce;
		this._isValid=isValid;
		this._description=description;
		this._creator=creator;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_name);
			sb.Append(_appID);
			sb.Append(_text);
			sb.Append(_assembly);
			sb.Append(_namesapce);
			sb.Append(_isValid);
			sb.Append(_description);
			sb.Append(_creator);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 模块名
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 所属应用
        /// </summary>
		public virtual string AppID
        {
            get { return  _appID; }
			set	{	_appID =  value;}
        }
		
		/// <summary>
        /// 模块显示名
        /// </summary>
		public virtual string Text
        {
            get { return  _text; }
			set	{	_text =  value;}
        }
		
		/// <summary>
        /// 程序集
        /// </summary>
		public virtual string Assembly
        {
            get { return  _assembly; }
			set	{	_assembly =  value;}
        }
		
		/// <summary>
        /// 命名空间
        /// </summary>
		public virtual string Namesapce
        {
            get { return  _namesapce; }
			set	{	_namesapce =  value;}
        }
		
		/// <summary>
        /// 是否有效
        /// </summary>
		public virtual short IsValid
        {
            get { return  _isValid; }
			set	{	_isValid =  value;}
        }
		
		/// <summary>
        /// 描述
        /// </summary>
		public virtual string Description
        {
            get { return  _description; }
			set	{	_description =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
