#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  ObjectRole
 * Descrption:
 * CreateDate: 2010/11/18 13:55:36
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;

namespace AgileEAP.Infrastructure.Domain
{
    public partial class ObjectRole : DomainObject<string>
    {
        #region Fields

        private string _roleID = string.Empty;
        private short _objectType = default(Int16);
        private string _objectID = string.Empty;


        #endregion

        #region Constructors
        public ObjectRole() { }


        public ObjectRole(string id, string roleID, short objectType, string objectID)
        {
            this.ID = id;
            this._roleID = roleID;
            this._objectType = objectType;
            this._objectID = objectID;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_roleID);
            sb.Append(_objectType);
            sb.Append(_objectID);

            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 角色ID
        /// </summary>
        public virtual string RoleID
        {
            get { return _roleID; }
            set { _roleID = value; }
        }

        /// <summary>
        /// 取值范围业务字典 ABF_PARTYTYPE
        ///机构、工作组、岗位、职务
        /// </summary>
        public virtual short ObjectType
        {
            get { return _objectType; }
            set { _objectType = value; }
        }

        /// <summary>
        /// 对象ID
        /// </summary>
        public virtual string ObjectID
        {
            get { return _objectID; }
            set { _objectID = value; }
        }

        #endregion
    }
}
