#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  Operator
 * Descrption:
 * CreateDate: 2010/11/18 13:55:34
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class Operator :DomainObject<string>
    {
        #region Fields
		
		private short _userType = default(Int16);
		private string _loginName = string.Empty;
		private string _userName = string.Empty;
		private string _password = string.Empty;
		private System.DateTime _expireTime = DateTime.Now;
		private short _authMode = default(Int16);
		private short _status = default(Int16);
        private string _skin = "Default";
		private System.DateTime _lastLogin = DateTime.Now;
		private System.DateTime _startTime = DateTime.Now;
		private System.DateTime _endTime = DateTime.Now;
		private string _mACCode = string.Empty;
		private string _clientIP = string.Empty;
		private string _ownerOrg = string.Empty;
		private string _email = string.Empty;
		private string _phone = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public Operator(){}
		
		
		public Operator(string id,short userType,string loginName,string userName,string password,System.DateTime expireTime,short authMode,short status,string skin,System.DateTime lastLogin,System.DateTime startTime,System.DateTime endTime,string mACCode,string clientIP,string ownerOrg,string email,string phone,string creator,System.DateTime createTime)
		{
		  this.ID=id;
		this._userType=userType;
		this._loginName=loginName;
		this._userName=userName;
		this._password=password;
		this._expireTime=expireTime;
		this._authMode=authMode;
		this._status=status;
		this._skin=skin;
		this._lastLogin=lastLogin;
		this._startTime=startTime;
		this._endTime=endTime;
		this._mACCode=mACCode;
		this._clientIP=clientIP;
		this._ownerOrg=ownerOrg;
		this._email=email;
		this._phone=phone;
		this._creator=creator;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_userType);
			sb.Append(_loginName);
			sb.Append(_userName);
			sb.Append(_password);
			sb.Append(_expireTime);
			sb.Append(_authMode);
			sb.Append(_status);
			sb.Append(_skin);
			sb.Append(_lastLogin);
			sb.Append(_startTime);
			sb.Append(_endTime);
			sb.Append(_mACCode);
			sb.Append(_clientIP);
			sb.Append(_ownerOrg);
			sb.Append(_email);
			sb.Append(_phone);
			sb.Append(_creator);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 用户类型
        /// </summary>
		public virtual short UserType
        {
            get { return  _userType; }
			set	{	_userType =  value;}
        }
		
		/// <summary>
        /// 登录名
        /// </summary>
		public virtual string LoginName
        {
            get { return  _loginName; }
			set	{	_loginName =  value;}
        }
		
		/// <summary>
        /// 操作员姓名
        /// </summary>
		public virtual string UserName
        {
            get { return  _userName; }
			set	{	_userName =  value;}
        }
		
		/// <summary>
        /// 密码
        /// </summary>
		public virtual string Password
        {
            get { return  _password; }
			set	{	_password =  value;}
        }
		
		/// <summary>
        /// 密码失效时间
        /// </summary>
		public virtual System.DateTime ExpireTime
        {
            get { return  _expireTime.ToSafeDateTime(); }
			set	{	_expireTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 本地密码认证、LDAP认证、等
        /// </summary>
		public virtual short AuthMode
        {
            get { return  _authMode; }
			set	{	_authMode =  value;}
        }
		
		/// <summary>
        /// 正常，挂起，注销，锁定...
        /// </summary>
		public virtual short Status
        {
            get { return  _status; }
			set	{	_status =  value;}
        }
		
		/// <summary>
        /// 用户登录后菜单的风格
        /// </summary>
        public virtual string Skin
        {
            get { return  _skin; }
			set	{	_skin =  value;}
        }
		
		/// <summary>
        /// 最近登录时间
        /// </summary>
		public virtual System.DateTime LastLogin
        {
            get { return  _lastLogin.ToSafeDateTime(); }
			set	{	_lastLogin =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 有效开始日期
        /// </summary>
		public virtual System.DateTime StartTime
        {
            get { return  _startTime.ToSafeDateTime(); }
			set	{	_startTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 有效截止日期
        /// </summary>
		public virtual System.DateTime EndTime
        {
            get { return  _endTime.ToSafeDateTime(); }
			set	{	_endTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 允许设置多个MAC
        /// </summary>
		public virtual string MACCode
        {
            get { return  _mACCode; }
			set	{	_mACCode =  value;}
        }
		
		/// <summary>
        /// 允许设置多个IP地址
        /// </summary>
		public virtual string ClientIP
        {
            get { return  _clientIP; }
			set	{	_clientIP =  value;}
        }
		
		/// <summary>
        /// 归属组织
        /// </summary>
		public virtual string OwnerOrg
        {
            get { return  _ownerOrg; }
			set	{	_ownerOrg =  value;}
        }
		
		/// <summary>
        /// 邮箱地址
        /// </summary>
		public virtual string Email
        {
            get { return  _email; }
			set	{	_email =  value;}
        }
		
		/// <summary>
        /// 联系电话
        /// </summary>
		public virtual string Phone
        {
            get { return  _phone; }
			set	{	_phone =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
