#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  Operate
 * Descrption:
 * CreateDate: 2010/11/18 13:55:34
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;

namespace AgileEAP.Infrastructure.Domain
{
    public partial class Operate :DomainObject<string>
    {
        #region Fields
		
		private string _operateName = string.Empty;
		private string _commandName = string.Empty;
		private string _commandArgument = string.Empty;
		private short _isValid = default(Int16);
		private short _isVerify = default(Int16);
		private int _sortOrder = default(Int32);
		private string _description = string.Empty;
		private string _ownerOrg = string.Empty;
		private short _runat = default(Int16);
		
		
        #endregion

        #region Constructors
		public Operate(){}
		
		
		public Operate(string id,string operateName,string commandName,string commandArgument,short isValid,short isVerify,int sortOrder,string description,string ownerOrg,short runat)
		{
		  this.ID=id;
		this._operateName=operateName;
		this._commandName=commandName;
		this._commandArgument=commandArgument;
		this._isValid=isValid;
		this._isVerify=isVerify;
		this._sortOrder=sortOrder;
		this._description=description;
		this._ownerOrg=ownerOrg;
		this._runat=runat;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_operateName);
			sb.Append(_commandName);
			sb.Append(_commandArgument);
			sb.Append(_isValid);
			sb.Append(_isVerify);
			sb.Append(_sortOrder);
			sb.Append(_description);
			sb.Append(_ownerOrg);
			sb.Append(_runat);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 操作名称
        /// </summary>
		public virtual string OperateName
        {
            get { return  _operateName; }
			set	{	_operateName =  value;}
        }
		
		/// <summary>
        /// 命令
        /// </summary>
		public virtual string CommandName
        {
            get { return  _commandName; }
			set	{	_commandName =  value;}
        }
		
		/// <summary>
        /// 命令参数
        /// </summary>
		public virtual string CommandArgument
        {
            get { return  _commandArgument; }
			set	{	_commandArgument =  value;}
        }
		
        ///// <summary>
        ///// 是否有效
        ///// </summary>
        //public virtual short IsValid
        //{
        //    get { return  _isValid; }
        //    set	{	_isValid =  value;}
        //}
		
		/// <summary>
        /// 是否验证
        /// </summary>
		public virtual short IsVerify
        {
            get { return  _isVerify; }
			set	{	_isVerify =  value;}
        }
		
		/// <summary>
        /// 序号
        /// </summary>
		public virtual int SortOrder
        {
            get { return  _sortOrder; }
			set	{	_sortOrder =  value;}
        }
		
        ///// <summary>
        ///// 说明
        ///// </summary>
        //public virtual string Description
        //{
        //    get { return  _description; }
        //    set	{	_description =  value;}
        //}
		
        ///// <summary>
        ///// 归属组织
        ///// </summary>
        //public virtual string OwnerOrg
        //{
        //    get { return  _ownerOrg; }
        //    set	{	_ownerOrg =  value;}
        //}
		
		/// <summary>
        /// 运行方式
        /// </summary>
		public virtual short Runat
        {
            get { return  _runat; }
			set	{	_runat =  value;}
        }
		
        #endregion
    }
}
