#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  Organization
 * Descrption:
 * CreateDate: 2010/11/18 13:55:37
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class Organization :DomainObject<string>
    {
        #region Fields
		
		private string _code = string.Empty;
		private string _parentID = string.Empty;
		private string _name = string.Empty;
		private int _grade = default(Int32);
		private short _type = default(Int16);
		private string _address = string.Empty;
		private string _zipCode = string.Empty;
		private string _governPosition = string.Empty;
		private string _governor = string.Empty;
		private string _manager = string.Empty;
		private string _contactMan = string.Empty;
		private string _contactPhone = string.Empty;
		private string _email = string.Empty;
		private string _webURL = string.Empty;
		private short _status = default(Int16);
		private string _area = string.Empty;
		private int _sortOrder = default(Int32);
		private string _description = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		private System.DateTime _modifier = DateTime.Now;
		private System.DateTime _modifyTime = DateTime.Now;
		private string _sapID = string.Empty;
		private string _corpID = string.Empty;
		
		
        #endregion

        #region Constructors
		public Organization(){}
		
		
		public Organization(string id,string code,string parentID,string name,int grade,short type,string address,string zipCode,string governPosition,string governor,string manager,string contactMan,string contactPhone,string email,string webURL,short status,string area,int sortOrder,string description,string creator,System.DateTime createTime,System.DateTime modifier,System.DateTime modifyTime,string sapID,string corpID)
		{
		  this.ID=id;
		this._code=code;
		this._parentID=parentID;
		this._name=name;
		this._grade=grade;
		this._type=type;
		this._address=address;
		this._zipCode=zipCode;
		this._governPosition=governPosition;
		this._governor=governor;
		this._manager=manager;
		this._contactMan=contactMan;
		this._contactPhone=contactPhone;
		this._email=email;
		this._webURL=webURL;
		this._status=status;
		this._area=area;
		this._sortOrder=sortOrder;
		this._description=description;
		this._creator=creator;
		this._createTime=createTime;
		this._modifier=modifier;
		this._modifyTime=modifyTime;
		this._sapID=sapID;
		this._corpID=corpID;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_code);
			sb.Append(_parentID);
			sb.Append(_name);
			sb.Append(_grade);
			sb.Append(_type);
			sb.Append(_address);
			sb.Append(_zipCode);
			sb.Append(_governPosition);
			sb.Append(_governor);
			sb.Append(_manager);
			sb.Append(_contactMan);
			sb.Append(_contactPhone);
			sb.Append(_email);
			sb.Append(_webURL);
			sb.Append(_status);
			sb.Append(_area);
			sb.Append(_sortOrder);
			sb.Append(_description);
			sb.Append(_creator);
			sb.Append(_createTime);
			sb.Append(_modifier);
			sb.Append(_modifyTime);
			sb.Append(_sapID);
			sb.Append(_corpID);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 机构代码
        /// </summary>
		public virtual string Code
        {
            get { return  _code; }
			set	{	_code =  value;}
        }
		
		/// <summary>
        /// 上级组织
        /// </summary>
		public virtual string ParentID
        {
            get { return  _parentID; }
			set	{	_parentID =  value;}
        }
		
		/// <summary>
        /// 机构名称
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 总行，分行，海外分行...
        /// </summary>
		public virtual int Grade
        {
            get { return  _grade; }
			set	{	_grade =  value;}
        }
		
		/// <summary>
        /// 总公司/总部部门/分公司/分公司部门...
        /// </summary>
		public virtual short Type
        {
            get { return  _type; }
			set	{	_type =  value;}
        }
		
		/// <summary>
        /// 机构地址
        /// </summary>
		public virtual string Address
        {
            get { return  _address; }
			set	{	_address =  value;}
        }
		
		/// <summary>
        /// 邮编
        /// </summary>
		public virtual string ZipCode
        {
            get { return  _zipCode; }
			set	{	_zipCode =  value;}
        }
		
		/// <summary>
        /// 机构主管岗位
        /// </summary>
		public virtual string GovernPosition
        {
            get { return  _governPosition; }
			set	{	_governPosition =  value;}
        }
		
		/// <summary>
        /// 机构主管人员
        /// </summary>
		public virtual string Governor
        {
            get { return  _governor; }
			set	{	_governor =  value;}
        }
		
		/// <summary>
        /// 机构管理员能够给本机构的人员进行授权，多个机构管理员之间用,分隔
        /// </summary>
		public virtual string Manager
        {
            get { return  _manager; }
			set	{	_manager =  value;}
        }
		
		/// <summary>
        /// 联系人
        /// </summary>
		public virtual string ContactMan
        {
            get { return  _contactMan; }
			set	{	_contactMan =  value;}
        }
		
		/// <summary>
        /// 联系电话
        /// </summary>
		public virtual string ContactPhone
        {
            get { return  _contactPhone; }
			set	{	_contactPhone =  value;}
        }
		
		/// <summary>
        /// 电子邮件
        /// </summary>
		public virtual string Email
        {
            get { return  _email; }
			set	{	_email =  value;}
        }
		
		/// <summary>
        /// 网站地址
        /// </summary>
		public virtual string WebURL
        {
            get { return  _webURL; }
			set	{	_webURL =  value;}
        }
		
		/// <summary>
        /// 机构状态
        /// </summary>
		public virtual short Status
        {
            get { return  _status; }
			set	{	_status =  value;}
        }
		
		/// <summary>
        /// 所属地域
        /// </summary>
		public virtual string Area
        {
            get { return  _area; }
			set	{	_area =  value;}
        }
		
		/// <summary>
        /// 序号
        /// </summary>
		public virtual int SortOrder
        {
            get { return  _sortOrder; }
			set	{	_sortOrder =  value;}
        }
		
		/// <summary>
        /// 描述
        /// </summary>
		public virtual string Description
        {
            get { return  _description; }
			set	{	_description =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 修改者
        /// </summary>
		public virtual System.DateTime Modifier
        {
            get { return  _modifier.ToSafeDateTime(); }
			set	{	_modifier =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// 修改时间
        /// </summary>
		public virtual System.DateTime ModifyTime
        {
            get { return  _modifyTime.ToSafeDateTime(); }
			set	{	_modifyTime =  value.ToSafeDateTime();}
        }
		
		/// <summary>
        /// SapID
        /// </summary>
		public virtual string SapID
        {
            get { return  _sapID; }
			set	{	_sapID =  value;}
        }
		
		/// <summary>
        /// 公司ID
        /// </summary>
		public virtual string CorpID
        {
            get { return  _corpID; }
			set	{	_corpID =  value;}
        }

        public virtual string OwnerOrg { get; set; }
		
        #endregion
    }
}
