#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  Position
 * Descrption:
 * CreateDate: 2010/11/18 13:55:37
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class Position :DomainObject<string>
    {
        #region Fields
		
		private string _code = string.Empty;
		private string _name = string.Empty;
		private string _dutyID = string.Empty;
		private string _appID = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public Position(){}
		
		
		public Position(string id,string code,string name,string dutyID,string appID,string creator,System.DateTime createTime)
		{
		  this.ID=id;
		this._code=code;
		this._name=name;
		this._dutyID=dutyID;
		this._appID=appID;
		this._creator=creator;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_code);
			sb.Append(_name);
			sb.Append(_dutyID);
			sb.Append(_appID);
			sb.Append(_creator);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 岗位代码
        /// </summary>
		public virtual string Code
        {
            get { return  _code; }
			set	{	_code =  value;}
        }
		
		/// <summary>
        /// 岗位名称
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 职务ID
        /// </summary>
		public virtual string DutyID
        {
            get { return  _dutyID; }
			set	{	_dutyID =  value;}
        }
		
		/// <summary>
        /// 应用ID
        /// </summary>
		public virtual string AppID
        {
            get { return  _appID; }
			set	{	_appID =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
