#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  Resource
 * Descrption:
 * CreateDate: 2010/11/18 13:55:34
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class Resource : DomainObject<string>
    {
        #region Fields

        private string _name = string.Empty;
        private string _text = string.Empty;
        private short _type = default(Int16);
        private string _parentID = string.Empty;
        private string _entry = string.Empty;
        private string _argument = string.Empty;
        private string _uRL = string.Empty;
        private int _sortOrder = default(Int32);
        private string _icon = string.Empty;
        private string _expandIcon = string.Empty;
        private short _openMode = default(Int16);
        private string _appID = string.Empty;
        private string _moduleID = string.Empty;
        private string _description = string.Empty;
        private string _ownerOrg = string.Empty;
        private string _creator = string.Empty;
        private System.DateTime _createTime = DateTime.Now;


        #endregion

        #region Constructors
        public Resource() { }


        public Resource(string id, string name, string text, short type, string parentID, string entry, string argument, string uRL, int sortOrder, string icon, string expandIcon, short openMode, string appID, string moduleID, string description, string ownerOrg, string creator, System.DateTime createTime)
        {
            this.ID = id;
            this._name = name;
            this._text = text;
            this._type = type;
            this._parentID = parentID;
            this._entry = entry;
            this._argument = argument;
            this._uRL = uRL;
            this._sortOrder = sortOrder;
            this._icon = icon;
            this._expandIcon = expandIcon;
            this._openMode = openMode;
            this._appID = appID;
            this._moduleID = moduleID;
            this._description = description;
            this._ownerOrg = ownerOrg;
            this._creator = creator;
            this._createTime = createTime;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_name);
            sb.Append(_text);
            sb.Append(_type);
            sb.Append(_parentID);
            sb.Append(_entry);
            sb.Append(_argument);
            sb.Append(_uRL);
            sb.Append(_sortOrder);
            sb.Append(_icon);
            sb.Append(_expandIcon);
            sb.Append(_openMode);
            sb.Append(_appID);
            sb.Append(_moduleID);
            sb.Append(_description);
            sb.Append(_ownerOrg);
            sb.Append(_creator);
            sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 资源名称
        /// </summary>
        public virtual string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        /// 资源显示名
        /// </summary>
        public virtual string Text
        {
            get { return _text; }
            set { _text = value; }
        }

        /// <summary>
        /// 资源类型
        /// </summary>
        public virtual short Type
        {
            get { return _type; }
            set { _type = value; }
        }

        /// <summary>
        /// 父资源
        /// </summary>
        public virtual string ParentID
        {
            get { return _parentID; }
            set { _parentID = value; }
        }

        /// <summary>
        /// 调用入口
        /// </summary>
        public virtual string Entry
        {
            get { return _entry; }
            set { _entry = value; }
        }

        /// <summary>
        /// 输入参数
        /// </summary>
        public virtual string Argument
        {
            get { return _argument; }
            set { _argument = value; }
        }

        /// <summary>
        /// 链接地址
        /// </summary>
        public virtual string URL
        {
            get { return _uRL; }
            set { _uRL = value; }
        }

        /// <summary>
        /// 序号
        /// </summary>
        public virtual int SortOrder
        {
            get { return _sortOrder; }
            set { _sortOrder = value; }
        }

        /// <summary>
        /// 闭合图标
        /// </summary>
        public virtual string Icon
        {
            get { return _icon; }
            set { _icon = value; }
        }

        /// <summary>
        /// 展开图标
        /// </summary>
        public virtual string ExpandIcon
        {
            get { return _expandIcon; }
            set { _expandIcon = value; }
        }

        /// <summary>
        /// 主窗口打开、弹出窗口打开...
        /// </summary>
        public virtual short OpenMode
        {
            get { return _openMode; }
            set { _openMode = value; }
        }

        ///// <summary>
        ///// 所属应用
        ///// </summary>
        //public virtual string AppID
        //{
        //    get { return _appID; }
        //    set { _appID = value; }
        //}

        ///// <summary>
        ///// 所属模块
        ///// </summary>
        //public virtual string ModuleID
        //{
        //    get { return _moduleID; }
        //    set { _moduleID = value; }
        //}

        /// <summary>
        /// 描述
        /// </summary>
        //public virtual string Description
        //{
        //    get { return _description; }
        //    set { _description = value; }
        //}

        /// <summary>
        /// 归属组织
        /// </summary>
        //public virtual string OwnerOrg
        //{
        //    get { return _ownerOrg; }
        //    set { _ownerOrg = value; }
        //}

        /// <summary>
        /// 创建者
        /// </summary>
        public virtual string Creator
        {
            get { return _creator; }
            set { _creator = value; }
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual System.DateTime CreateTime
        {
            get { return _createTime.ToSafeDateTime(); }
            set { _createTime = value.ToSafeDateTime(); }
        }

        #endregion

        public virtual List<Operate> Operates
        {
            get;
            set;
        }

        public virtual short ShowNavigation
        {
            get;
            set;
        }

        public virtual short ShowToolBar
        {
            get;
            set;
        }
    }
}
