#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AgileEAP.Infrastructure
 * Module:  UploadFile
 * Descrption:
 * CreateDate: 2010/12/27 20:19:51
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using AgileEAP.Core.Domain;
using AgileEAP.Core.Extensions;



namespace AgileEAP.Infrastructure.Domain
{
    public partial class UploadFile :DomainObject<string>
    {
        #region Fields
		
		private string _fileName = string.Empty;
		private string _uniqueName = string.Empty;
		private short _fileType = default(Int16);
		private string _catalogID = string.Empty;
		private string _filePath = string.Empty;
		private string _description = string.Empty;
		private string _ownerOrg = string.Empty;
		private string _creator = string.Empty;
        private string _bizID = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public UploadFile(){}


        public UploadFile(string id, string fileName, string uniqueName, short fileType, string catalogID, string filePath, string description, string ownerOrg, string creator, System.DateTime createTime, string bizID)
		{
		  this.ID=id;
		this._fileName=fileName;
		this._uniqueName=uniqueName;
		this._fileType=fileType;
		this._catalogID=catalogID;
		this._filePath=filePath;
		this._description=description;
		this._ownerOrg=ownerOrg;
		this._creator=creator;
		this._createTime=createTime;
        this._bizID = bizID;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_fileName);
			sb.Append(_uniqueName);
			sb.Append(_fileType);
			sb.Append(_catalogID);
			sb.Append(_filePath);
			sb.Append(_description);
			sb.Append(_ownerOrg);
			sb.Append(_creator);
			sb.Append(_createTime);
            sb.Append(_bizID);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 文件名称
        /// </summary>
		public virtual string FileName
        {
            get { return  _fileName; }
			set	{	_fileName =  value;}
        }

        public virtual string BizID
        {
            get { return _bizID; }
            set { _bizID = value; }
        }
		/// <summary>
        /// 唯一名称
        /// </summary>
		public virtual string UniqueName
        {
            get { return  _uniqueName; }
			set	{	_uniqueName =  value;}
        }
		
		/// <summary>
        /// 文件类型
        /// </summary>
		public virtual short FileType
        {
            get { return  _fileType; }
			set	{	_fileType =  value;}
        }
		
		/// <summary>
        /// 所在目录
        /// </summary>
		public virtual string CatalogID
        {
            get { return  _catalogID; }
			set	{	_catalogID =  value;}
        }
		
		/// <summary>
        /// 文件路径
        /// </summary>
		public virtual string FilePath
        {
            get { return  _filePath; }
			set	{	_filePath =  value;}
        }
		
		/// <summary>
        /// 描述
        /// </summary>
		public virtual string Description
        {
            get { return  _description; }
			set	{	_description =  value;}
        }
		
		/// <summary>
        /// 归属组织
        /// </summary>
		public virtual string OwnerOrg
        {
            get { return  _ownerOrg; }
			set	{	_ownerOrg =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
